name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$ENVS" > .env'
        shell: bash
        env:
          ENVS: ${{secrets.ENVS}}
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spotify-notifier-bot"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
